In [2]:

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import os

REV_CLASS_MAP = {


    0: "nas1802-3-6",
    1: "nas1802-3-7",



   # 0: "m59557-16",
    #1: "m59557-20",
    #2: "nas1802-3-7",
    #3: "nas1802-3-9",
    #4: "nas6305-10",
    #5: "v647p23b",

}

def mapper(val):
    return REV_CLASS_MAP[val]

model = load_model("models/image_data_blue_light_split_sq350_e120_tb40_vb40_aug-hor-rotran20-briran0_8;1_2).h5")

# image folder
folder_path = 'dataset/image_data_blue_light_split/test/'
roi_square_size = 350
test_batch_size = 10

test_datagen = ImageDataGenerator()

test_it = test_datagen.flow_from_directory(
    os.path.abspath(folder_path ),
    target_size=(roi_square_size, roi_square_size),
    class_mode='categorical',
    batch_size=test_batch_size
)


# stack up images list to pass for prediction
# classes = model.predict(images, batch_size=1)
# loss, acc = model.evaluate(test_it, verbose=2)
prediction = model.predict(test_it, verbose=1)
type(prediction)
print(prediction)
# print(classes)


Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 350, 350, 3) 0                                            
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 175, 175, 64) 1792        input_2[0][0]                    
__________________________________________________________________________________________________
maxpool1 (MaxPooling2D)         (None, 87, 87, 64)   0           conv1[0][0]                      
__________________________________________________________________________________________________
fire2_squeeze (Conv2D)          (None, 87, 87, 16)   1040        maxpool1[0][0]                   
____________________________________________________________________________________________

In [6]:
np.set_printoptions(formatter={ 'float':lambda x: "{0:0.3f}".format(x)})
print(prediction)
print(prediction.shape)

[[0.000 0.000 0.000 ... 0.000 0.965 0.000]
 [0.051 0.161 0.788 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 1.000]
 ...
 [0.027 0.000 0.000 ... 0.342 0.000 0.000]
 [0.027 0.000 0.000 ... 0.435 0.000 0.000]
 [0.935 0.021 0.020 ... 0.024 0.000 0.000]]
(171, 9)
